//
// Created by William on 2025-10-19.
//

#ifndef WILLENGINETESTBED_DESCRIPOR_BUFFER_BINDLESS_RESOURCES_H
#define WILLENGINETESTBED_DESCRIPOR_BUFFER_BINDLESS_RESOURCES_H

namespace Renderer
{
class descripor_buffer_bindless_resources
{};
} // Renderer

#endif //WILLENGINETESTBED_DESCRIPOR_BUFFER_BINDLESS_RESOURCES_H